/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author josep
 */
public class ReporteCedula extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteCedula
     */
    public ReporteCedula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtCedula = new javax.swing.JTextField();
        jbtnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Buscar por Cédula:");

        jbtnReporte.setText("Reporte");
        jbtnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jbtnReporte)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnReporte)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReporteActionPerformed
        try {
            // Validar que se ingresó una cédula
            String cedula = jtxtCedula.getText().trim();

            if (cedula.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese una cédula");
                return;
            }

            Conexion cc = new Conexion();
            Connection cn = cc.conectar();

            // Crear parámetros
            Map<String, Object> parametros = new HashMap<>();
            parametros.put("cedula", cedula);

            // Cargar el archivo .jasper YA COMPILADO
            InputStream archivo = getClass().getResourceAsStream("/Reportes/report1.jasper");

            if (archivo == null) {
                JOptionPane.showMessageDialog(this, "No se encuentra el archivo del reporte (.jasper)");
                return;
            }

            // Cargar reporte
            JasperReport reporte = (JasperReport) JRLoader.loadObject(archivo);
            JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);

            // Cerrar recursos
            archivo.close();
            cn.close();

            // VERIFICAR SI HAY DATOS
            if (imprimir.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron datos para la cédula: " + cedula);
                return;
            }

            // CREAR INTERNAL FRAME PARA MOSTRAR EL REPORTE DENTRO DEL DESKTOP
            javax.swing.JInternalFrame reportFrame = new javax.swing.JInternalFrame(
                    "Reporte Estudiante - Cédula: " + cedula,
                    true, true, true, true
            );

            // Crear visor embebido (JRViewer en lugar de JasperViewer)
            net.sf.jasperreports.view.JRViewer viewer = new net.sf.jasperreports.view.JRViewer(imprimir);

            // Configurar el internal frame
            reportFrame.getContentPane().add(viewer);
            reportFrame.setSize(800, 600);
            reportFrame.setVisible(true);

            // Obtener el desktop pane del padre (Principal)
            java.awt.Container parent = this.getParent();
            if (parent instanceof javax.swing.JDesktopPane) {
                javax.swing.JDesktopPane desktop = (javax.swing.JDesktopPane) parent;
                desktop.add(reportFrame);

                // Centrar el internal frame
                reportFrame.setLocation(
                        (desktop.getWidth() - reportFrame.getWidth()) / 2,
                        (desktop.getHeight() - reportFrame.getHeight()) / 2
                );

                reportFrame.toFront();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo embebir el reporte en el desktop");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al generar el reporte: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbtnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteCedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteCedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteCedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteCedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteCedula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnReporte;
    private javax.swing.JTextField jtxtCedula;
    // End of variables declaration//GEN-END:variables
}
